package team.hs.libsys.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_author
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_price
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private BigDecimal bookPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_numbers
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private Integer bookNumbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_buy_time
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    private Date bookBuyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param categoryId the value for book.category_id
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_author
     *
     * @return the value of book.book_author
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_author
     *
     * @param bookAuthor the value for book.book_author
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_price
     *
     * @return the value of book.book_price
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public BigDecimal getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_price
     *
     * @param bookPrice the value for book.book_price
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookPrice(BigDecimal bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_numbers
     *
     * @return the value of book.book_numbers
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public Integer getBookNumbers() {
        return bookNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_numbers
     *
     * @param bookNumbers the value for book.book_numbers
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookNumbers(Integer bookNumbers) {
        this.bookNumbers = bookNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_buy_time
     *
     * @return the value of book.book_buy_time
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public Date getBookBuyTime() {
        return bookBuyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_buy_time
     *
     * @param bookBuyTime the value for book.book_buy_time
     *
     * @mbg.generated Sat Nov 24 09:58:32 CST 2018
     */
    public void setBookBuyTime(Date bookBuyTime) {
        this.bookBuyTime = bookBuyTime;
    }
}